image: node:14.17-slim

pipelines:
  branches:
    feature/s3-deploy-test:
      - step:
          name: Installing & Running Tests
          caches:
            - node
          script:
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
            #- npm run test
      - step:
          name: Build
          script:
            #- npm install --production
            #- REACT_APP_ENVIRONMENT=production npm run build
            - npm install
            - npm run build:dev
            #- mkdir build
            #- tar -czvf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C build .
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:1.0.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_DEV
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_DEV
                AWS_DEFAULT_REGION: $AWS_ZONE_DEV
                S3_BUCKET: $PRODUCTION_BUCKET_NAME
                ACL: "public-read"
                LOCAL_PATH: "build"
#      - step:
#          name: Invalidate Cloudfront Cache
#          script:
#            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
#              variables:
#                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
#                DISTRIBUTION_ID: $PRODUCTION_DISTRIBUTION_ID
#  branches:
#    s3-deploy-test:
#      - step:
#          name: Installing & Running Tests
#          caches:
#            - node
#          script:
#            - rm -rf package-lock.json
#            - rm -rf node_modules
#            - npm install
#            - npm run test