image: node:14.17-slim

pipelines:
  branches:
    feature/s3-deploy-test:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build:dev
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:1.0.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_ZONE_DEV
                S3_BUCKET: $PRODUCTION_BUCKET_NAME
                ACL: "public-read"
                LOCAL_PATH: "build"
      - step:
          name: Invalidate Cloudfront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_ZONE_DEV
                DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID