export default {
  INDEX: '/',
  ADMIN: '/admin',
  REPORTS: '/admin/reports',
  REPORTS_TRANSACTION: '/admin/reports/transaction',
  REPORTS_ACTUAL_STOK: '/admin/reports/actualStock',
  REPORTS_MOVEMENT_STOK: '/admin/reports/actualStock',
  OPERATION_CHAIN: '/admin/operations/chain',
  OPERATION_EDIT_CHAIN: '/admin/operations/chain/:id',
  OPERATION_EDIT_PROMO: '/admin/operations/chain/:id/promo/:PromoId',
  OPERATION_NEW_PROMO: '/admin/operations/chain/:id/promo',
  OPERATIONS: '/admin/operations',
  USER: '/admin/user',
  CONFIGURATION: '/admin/configurations',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgotPassword',
  CHANGE_PASSWORD: '/changePassword',
  OPERATION_AUDIT: '/admin/operations/auditories',
  OPERATION_AUDIT_INPROCESS_DETAIL:
    '/admin/operations/auditories/inProcess/:id',
  OPERATION_AUDIT_DONE_DETAIL: '/admin/operations/auditories/done/:id',
  INTERACTIVE_CONTENT: '/admin/configurations/interactiveContent',
  INTERACTIVE_CONTENT_EDIT: '/admin/configurations/interactiveContent/:id',
  INTERACTIVE_CONTENT_NEW: '/admin/configurations/newInteractiveContent',
};
