export const types = {

    CHANGE_HISTORY :'CHANGE_HISTORY',
    CHANGE_REASONS_CANCELED :'CHANGE_REASONS_CANCELED',
    CHANGE_REASONS_CONFIRM :'CHANGE_REASONS_CONFIRM',
    CHANGE_FINISH_MODAL :'CHANGE_FINISH_MODAL',
    TEST:'TEST'
}

