export const CHANGE_HISTORY = 'CHANGE_HISTORY';
export const CHANGE_REASONS_CANCELED = 'CHANGE_REASONS_CANCELED';
export const CHANGE_REASONS_CONFIRM = 'CHANGE_REASONS_CONFIRM';
export const CHANGE_FINISH_MODAL = 'CHANGE_FINISH_MODAL';